# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs

language: node_js

node_js:
  - "node"
  - "lts/*"

install:
  - npm install

script:
  - npm run lint
  - npm run build

notifications:
  email: false
